### ISSUE TITLE
Unknown property axisbg

### ISSUE THREAD

**Issue by aque** [jawatson/pythonprop#7]
Running pythonprop 0.27 under OSX 10.13.6 MacPorts with python 3.5.5 and matplotlib 2.2.2. I am getting the following error when opening the Area Prediction plot.

```
Traceback (most recent call last):
  File "/opt/local/lib/python3.5/site-packages/pythonprop/voaAreaPlotgui.py", line 224, in run_plot
    parent = plot_parent)
  File "/opt/local/lib/python3.5/site-packages/pythonprop/voaAreaPlot.py", line 237, in __init__
    axisbg = 'white')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/figure.py", line 1239, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_subplots.py", line 77, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 539, in __init__
    self.update(kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/artist.py", line 888, in update
    for k, v in props.items()]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/artist.py", line 888, in <listcomp>
    for k, v in props.items()]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/artist.py", line 881, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property axisbg
```

**Comment by jawatson** [comment]
Thanks for the bug report.  Basemap is now in maintenance mode and is making calls to deprecated matplotlib functions as described in the following post;

https://stackoverflow.com/questions/50691151/axessubplot-object-has-no-attribute-get-axis-bgcolor

I've started work on a version that replaces cartopy which is the long-term fix.
